openapi: 3.0.3
info:
  title: Dog API Documentation
  description: |
    # About 
      **[Dog API](https://dog.ceo/dog-api/)** is the internet's largest collection of open source dog pictures.
  license:
    name: MIT License
    url: https://opensource.org/license/MIT
  version: 0.0.1
server:
  url: https://dog.ceo/api
  description: Production server
externalDocs:
  description: External Documentation
  url: https://dog.ceo/dog-api/documentation/
tags:
  - name: List All 
    description: List all breeds
  - name: Random 
    description: Returns a random image
  - name: By Breed
    description: Searches you can do based on breed.
  - name: By Sub-Breed
    description: Searches you can do using sub-breed.
host: https://dog.ceo
basePath: /api
schemes:
  - https
paths:
  /breeds/list/all:
    get:
      tags:
        - List All 
      summary: List all dog breeds
      description: Returns the list of dog breeds available in Dog api
      operationId: getBreeds
      responses:
        '200':
          description: A list of dog breeds
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: object
                    additionalProperties:
                      type: array
                      items:
                        type: string
                    example: [ "affenpinscher": [], "african": [], "airedale": [], "akita": []]
                    description: A map of dog breeds to their sub-breeds (if any)
                  status:
                    type: string
                    enum: [success, error]
                    description: Status of the API response
                required:
                  - message
                  - status
  /breeds/image/random:
    get:
      tags:
        - Random
      summary: Get random image
      description: Returns a single random image from all dogs collection
      operationId: breedsImageRandom
      responses:
        '200':
          description: A random dog image
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    format: uri
                    example: "https://images.dog.ceo/breeds/mastiff-bull/n02108422_4793.jpg"
                    description: URL of the dog image
                  status:
                    type: string
                    enum: [success, error]
                    description: Status of the API response
                required:
                  - message
                  - status
  /breed/{breedId}/images:
    get:
      tags:
        - By Breed
      summary: Returns a lists of images for a specific dog breed.
      description: Returns a list of image URLs for the specified dog breed, e.g. hound.
      operationId: allBreedImages
      parameters:
        - name: breedId
          in: path
          required: true
          description: The ID or name of the dog breed (e.g. `hound-afghan`)
          schema:
            type: string
      responses:
        '200':
          description: A list of image URLs for the breed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: array
                    items:
                      type: string
                      format: uri
                    description: List of dog image URLs
                  status:
                    type: string
                    enum: [success, error]
                    description: Status of the response
                required:
                  - message
                  - status
        '400':
          description: Invalid breed ID supplied
        '404':
          description: Breed not found
  /breed/{breedId}/images/random:
    get:
      summary: Get a random image for a specific dog breed
      description: Returns a single random image URL for the specified dog breed.
      parameters:
        - name: breedId
          in: path
          required: true
          description: The ID or name of the dog breed (e.g. `mastiff-bull`, `hound-afghan`)
          schema:
            type: string
      responses:
        '200':
          description: A random image URL for the breed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    format: uri
                    description: URL of the dog image
                  status:
                    type: string
                    enum: [success, error]
                    description: Status of the response
                required:
                  - message
                  - status
        '400':
          description: Invalid breed ID supplied
        '404':
          description: Breed not found
  /breed/hound/images/random/{number}:
    get:
      summary: Get multiple random images for the "hound" breed
      description: Returns a specified number of random image URLs for the "hound" breed.
      parameters:
        - name: number
          in: path
          required: true
          description: Number of random images to return
          schema:
            type: integer
            minimum: 1
            maximum: 50  # adjust based on your API limits
      responses:
        '200':
          description: A list of random image URLs for the hound breed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: array
                    items:
                      type: string
                      format: uri
                    description: List of random dog image URLs
                  status:
                    type: string
                    enum: [success, error]
                    description: Status of the response
                required:
                  - message
                  - status
        '400':
          description: Invalid number supplied
        '404':
          description: Breed not found
  /breed/{subbreedId}/list:
    get:
      summary: Get list of sub-breeds for a specific breed
      description: Returns a list of sub-breed names for the specified dog breed.
      parameters:
        - name: subbreedId
          in: path
          required: true
          description: The ID or name of the dog breed (e.g., `bulldog`, `hound`)
          schema:
            type: string
      responses:
        '200':
          description: A list of sub-breeds for the specified breed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: array
                    items:
                      type: string
                    description: List of sub-breed names
                  status:
                    type: string
                    enum: [success, error]
                    description: Status of the response
                required:
                  - message
                  - status
        '400':
          description: Invalid breed name supplied
        '404':
          description: Breed not found or has no sub-breeds
